-- 코드를 입력하세요
SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM (  SELECT PLACES.HOST_ID, COUNT(HOST_ID) AS HOST_COUNT
        FROM PLACES
        GROUP BY HOST_ID) AS A, PLACES
WHERE A.HOST_COUNT >= 2 AND PLACES.HOST_ID = A.HOST_ID;