-- ECOLI_DATA 대장균 개체의 ID, 부모 개체의 ID, 개체의 크기, 분화되어 나온 날짜, 개체의 형질
SELECT M.YEAR, (M.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM ECOLI_DATA D
LEFT JOIN   (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
            FROM ECOLI_DATA
            GROUP BY YEAR) AS M 
ON M.YEAR = YEAR(D.DIFFERENTIATION_DATE)
ORDER BY M.YEAR, YEAR_DEV;