-- HR_DEPARTMENT 부서 ID, 국문 부서명, 영문 부서명, 부서 위치
-- HR_EMPLOYEES 사번, 성명, 부서 ID, 직책, 이메일, 전화번호, 입사일, 연봉

SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT D
RIGHT JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY AVG_SAL DESC;