-- USED_GOODS_BOARD 게시글 ID, 작성자 ID, 게시글 제목, 게시글 내용, 가격, 작성일, 거래상태, 조회수
-- USED_GOODS_FILE 파일 ID, 파일 확장자, 파일 이름, 게시글 ID
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
SELECT B.BOARD_ID
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
ORDER BY B.VIEWS DESC
LIMIT 1)
ORDER BY FILE_ID DESC;